export {default as Navbar} from './Navmenu'
export {default as Homepage} from './Homepage'
export {default as Exchanges} from './Exchanges'
export {default as News} from './News'
export {default as CryptoDetails} from './CryptoDetails'
export {default as CryptoKnights} from './CrptoKnights'
export {default as Footer} from './Footer'